### ISSUE TITLE
default screen sizes of components 

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#568] opened 2016-03-25 15:29 UTC
some components have default screen sizes (under water) that are too high. For instance if you forget to set a screen size for the Search component, the search screen in the viewer will be so high, that the information is not visible in the screen.

**Comment by NiekBouma** [comment] 2016-03-30 13:14
in flamingo4.b3p.nl it is easy to forget to set a screen size. By reusing the defaults again, it is prevented that the information is invisible on the screen.

**Comment by mtoonen** [comment] 2016-03-30 15:06
Which components?

**Comment by NiekBouma** [comment] 2016-03-30 15:16
All 45 components that can be selected in the Layout with components. Geert knows more about it.

**Comment by NiekBouma** [comment] 2016-04-12 14:14
when you enter a value lower than the minimal value for height or width, you do not get an error message and you are able to save the input. However, Flamingo uses the minimal values in the application. This is confusing for users: they should get a red frame around the invalid value(s) and an error message like: 'the value you entered is lower than the minimal value' when trying to save the screen.

**Comment by geertplaisier** [comment] 2016-04-14 16:13
Added validation message in 30819f66e7c201a4b164a33ee441aa5377d3993b

**Comment by geertplaisier** [comment] 2016-04-14 16:44
@NiekBouma Please check if this is fixed in the latest snapshot release. If the problem is fixed, please close this issue.

**Closed** 2016-04-29 14:27 UTC
Labels: Testen
