### ISSUE TITLE
Title of component shown twice when used in tab

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#873] opened 2017-06-19 14:15 UTC
### Version
4.8

### Browser info
chrome

### URL
middendelfland.flamingo4.nl

### Where?
viewer with tabbed side panel

### What happened
A component normally has a title. When used in a tab the title is used as as tablabel. The feature info component now show the component title twice: once in the tab and once in the component

### What did you expect?
Whenever the title is used in the tab, the title should not be used as a header in the component.

**Comment by Tom-Kooy** [comment] 2017-07-12 08:17
Workarround:
Use script below in the HTMLcompontent :

<script>
var delayMillis = 500; //0.5 second

setText(function() {
 document.getElementById("ext-element-5").innerHTML = "";
}, delayMillis);

window.onload = setText;
</script>

Where ext-element-5" is used, use the name of the component you want to change. There is a short delay build in, because sometimes the text is created after the script has run.

**Comment by mtoonen** [comment] 2017-07-13 07:29
Duplicate of #803.

**Closed** 2017-07-13 07:30 UTC
Labels: bug
