### ISSUE TITLE
bookmark field sizes

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#567] opened 2016-03-25 15:26 UTC
If the bookmark and compact link screens would be higher the complete bookmark could be shown

**Comment by NiekBouma** [comment] 2016-03-30 13:12
in flamingo4.b3p.nl http://flamingo4.b3p.nl/viewer/app/Solparc%20-%20Meldingen%20openbare%20ruimte/v1 for example, especially when a resolution of 1024 x 768 is used, the bookmark is not completely visible. By making the boxed slightly higher, they would be completely visible.

**Comment by geertplaisier** [comment] 2016-04-14 16:44
@NiekBouma Please check if this is fixed in the latest snapshot release. If the problem is fixed, please close this issue.

**Closed** 2016-04-29 14:27 UTC
Labels: Testen
