### ISSUE TITLE
Print options for A5 and A0 are visible, but not supported in print component

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#869] opened 2017-06-16 15:30 UTC
### Version
4.8.1 and 5.0.0 beta-8

### Browser info
any

### URL
http://flamingo4.b3p.nl/viewer/app/Gemeente_Goeree_Overflakkee_case_1/v1

### Where?
viewer

### What happened
When choosing the options for a print in the print component, it is possible to select A5 and A0 formats, but selecting them and clicking 'print as pdf' doesn't work

### What did you expect?
since it's not supported by Flamingo (only printstylesheets for A3 and A4) it should be not be offered as an option, or printstylesheets for A0 and A5 should be added.

**Comment by mprins** [comment] 2017-06-19 08:52
closing as this is a duplicate of #756, though you are welcome to provide (example) xsl files for A5 and A0 as that is all that is missing.
The files should be named:

- A5_Landscape.xsl
- A5_Portrait.xsl
- A0_Landscape.xsl
- A0_Portrait.xsl

A3 and A4 examples are available in: https://github.com/flamingo-geocms/flamingo/tree/master/viewer/src/main/webapp/WEB-INF/xsl/print/

**Closed by mprins** 2017-06-19 08:52 UTC
Labels: duplicate
