### ISSUE TITLE
Lay-out of mash-up cannot be dependant of lay-out of parent

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#749] opened 2017-01-10 15:01 UTC
### Version
flamingo 4.7.10-rc3

### Browser info
Firefox

### URL
viewer-admin of maps.vlaardingen.nl -> application Vlaardingen_test_b3p v1 & Vlaardingen_Test2_b3p v1 is are mash-ups of Vlaardingen v1

### Where?
Viewer-admin

### What happened
Made a mash-up (Vlaardingen_test_b3p v1) and did not check the box 'Moeten wijzigingen aan de componenten in de moederapplicatie ook doorwerken in de mashup?'. Changed the tooltip in the Search component in the parent, no change in the search component of the mash-up. 
Then i made a mash-up (Vlaardingen_Test2_b3p v1) and did check the box 'Moeten wijzigingen aan de componenten in de moederapplicatie ook doorwerken in de mashup?'. Changed the tooltip in the Search component in the parent, no change in the search component of the mash-up. 

### What did you expect?
I expected a change in the tooltip of Vlaardingen_Test2_b3p v1 after changing the tooltip of the parent

### Reproduce
See 'What happened'

### Server log
no relevant server log

**Comment by mtoonen** [comment] 2017-01-17 10:38
Duplicate of #737

**Closed by mtoonen** 2017-01-17 10:38 UTC
Labels: duplicate
