### ISSUE TITLE
cannot remove WFS attribuutbron

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#441] opened 2015-10-06 09:30 UTC
While trying to remove a WFS attribuutbron (that lists no use in the usage matrix) the following exception occurs:

```
HTTP Status 500 - Unhandled exception in exception handler.

type Exception report

message Unhandled exception in exception handler.

description The server encountered an internal error (Unhandled exception in exception handler.) that prevented it from fulfilling this request.

exception

net.sourceforge.stripes.exception.StripesServletException: Unhandled exception in exception handler.
    net.sourceforge.stripes.exception.DefaultExceptionHandler.handle(DefaultExceptionHandler.java:167)
    net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:250)
    nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
root cause

javax.persistence.RollbackException: Error while committing the transaction
    org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:93)
    nl.b3p.viewer.admin.stripes.AttributeSourceActionBean.delete(AttributeSourceActionBean.java:133)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
    org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:52)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:196)
    org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:126)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:175)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
    net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
    net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
    net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
    nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
root cause

javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
    org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387)
    org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1315)
    org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:81)
    nl.b3p.viewer.admin.stripes.AttributeSourceActionBean.delete(AttributeSourceActionBean.java:133)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
    org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:52)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:196)
    org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:126)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:175)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
    net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
    net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
    net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
    nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
root cause

org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
    org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
    org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
    org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
    org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
    org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:189)
    org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
    org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
    org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
    org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
    org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
    org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
    nl.b3p.viewer.admin.stripes.AttributeSourceActionBean.delete(AttributeSourceActionBean.java:133)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
    org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:52)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:196)
    org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:126)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:175)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
    net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
    net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
    net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
    nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
root cause

java.sql.BatchUpdateException: Batch entry 0 delete from feature_source where id=22 was aborted.  Call getNextException to see the cause.
    org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2744)
    org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
    org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
    org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2893)
    org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:298)
    org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:298)
    org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
    org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
    org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
    org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:189)
    org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
    org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
    org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
    org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
    org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
    org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
    nl.b3p.viewer.admin.stripes.AttributeSourceActionBean.delete(AttributeSourceActionBean.java:133)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:467)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
    org.stripesstuff.plugin.session.SessionStoreInterceptor.intercept(SessionStoreInterceptor.java:52)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.security.SecurityInterceptor.interceptEventHandling(SecurityInterceptor.java:196)
    org.stripesstuff.plugin.security.SecurityInterceptor.intercept(SecurityInterceptor.java:126)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:175)
    net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
    net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
    net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:465)
    net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
    net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:247)
    nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
```

**Comment by mprins** [comment] 2015-10-09 13:00
the WFS source was generated during map service import

**Comment by geertplaisier** [comment] 2016-02-18 13:10
Is this attribute source used in search somewhere?

**Comment by mprins** [comment] 2016-02-18 14:47
don't remember

**Comment by mtoonen** [comment] 2017-03-01 08:17
Cannot reproduce, closing.

**Closed by mtoonen** 2017-03-01 08:17 UTC
Labels: bug, viewer-admin
