### ISSUE TITLE
Application list in viewer-admin shows doudbles

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#486] opened 2015-12-07 08:59 UTC
One of the applications in the list of applications in pzh.b3p.nl/viewer-admin is shown twice, while one of the applications is not shown at all. 
Page 1 of 3 ends in this case with 'Cultuur_historische_atlas v5 Backup' (id: 28) and page 2 of 3 starts with 'Cultuur_historische_atlas v5 Backup' (id: 28). 'Cultuur_historische_atlas v4' (id: 27) on the other hand is not shown at all. 

The getGridData request for page 1 (http://pzh.b3p.nl/viewer-admin/action/chooseapplication/getGridData?_dc=1449477531197&page=1&start=0&limit=10&sort=name&dir=ASC) shows:
{"totalCount":22,"gridrows":[{"id":19,"name":"AAA v1","owner":"","published":"Nee"},{"id":5,"name":"Abebe v1","owner":"","published":"Nee"},{"id":26,"name":"basis v1","owner":"","published":"Nee"},{"id":25,"name":"Bijenlandschap v1","owner":"","published":"Nee"},{"id":17,"name":"Bodematlas v1","owner":"","published":"Nee"},{"id":10,"name":"Bodematlas_test v1","owner":"","published":"Nee"},{"id":9,"name":"Cultuur historische atlas v1","owner":"","published":"Nee"},{"id":21,"name":"Cultuur historische atlas v2","owner":"","published":"Nee"},{"id":8,"name":"Cultuur historische atlas v10","owner":"","published":"Nee"},{"id":28,"name":"Cultuur_historische_atlas v5 Backup","owner":"","published":"Nee"}]}

The getGridData for Page 2 (http://pzh.b3p.nl/viewer-admin/action/chooseapplication/getGridData?_dc=1449477579219&page=2&start=10&limit=10&sort=name&dir=ASC) shows: 
{"totalCount":22,"gridrows":[{"id":28,"name":"Cultuur_historische_atlas v5 Backup","owner":"","published":"Nee"},{"id":29,"name":"Cultuur_historische_atlas v6 Backup","owner":"","published":"Nee"},{"id":3,"name":"Meine v1","owner":"","published":"Nee"},{"id":6,"name":"Niek TD","owner":"","published":"Ja"},{"id":14,"name":"Recreatiegebieden","owner":"","published":"Ja"},{"id":12,"name":"template v1","owner":"","published":"Nee"},{"id":20,"name":"Test Archeologie v1","owner":"","published":"Nee"},{"id":7,"name":"Test Gerard","owner":"","published":"Ja"},{"id":2,"name":"Testje v1","owner":"","published":"Nee"},{"id":24,"name":"TestNiels v0.1","owner":"","published":"Nee"}]}

When filtering this list for 'Cultuur', six applications are shown: 'Cultuur_historische_atlas v4' (id: 27) and 'Cultuur_historische_atlas v5 Backup' (id: 28) are now both shown.

**Comment by mprins** [comment] 2015-12-08 11:27
This may be duplicate of #55

**Closed** 2017-04-07 14:10 UTC
Labels: bug, viewer-admin
