### ISSUE TITLE
compact bookmark fails to start map

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#499] opened 2015-12-18 15:08 UTC
> EKU 18/12: Compact link verzenden doet het niet: http://ibis.b3p.nl/app/IBISPUBLIEK?bookmark=9695bb1298944dd7b65f8081eb4a27f8 

terwijl grote link 
http://ibis.b3p.nl/app/IBISPUBLIEK?layers=877,878,880,884,886,887,888&extent=204071.74036488,451492.11070417,205462.78036488,452449.71070417&levelOrder=463,464,461,459,460,458,457&drawing1=%7B%22features%22%3A%5B%7B%22id%22%3A%22OpenLayers_Feature_Vector_288%22%2C%22wktgeom%22%3A%22POLYGON((204862.78036488%20452013.15070417%2C205030.78036488%20451801.47070417%2C204661.18036488%20451845.15070417%2C204862.78036488%20452013.15070417))%22%2C%22color%22%3A%22993366%22%7D%5D%7D& 
het wel doet

**Comment by mprins** [comment] 2015-12-18 15:11
initial check suggest something goes wrong in the ViewerController:

```
Uncaught TypeError: Cannot read property 'background' of undefinedExt.define.initAppLayer @ ViewerController.js:591
Ext.define.initLevel @ ViewerController.js:615
Ext.define.initLayers @ ViewerController.js:576
Ext.define.initLayers @ ViewerController.js:569(anonymous function) @ ViewerController.js:365
this.app.appLayers
```

**Comment by mprins** [comment] 2015-12-18 15:33
This caused by a layer id (888) that is not part of the map.

**Comment by mtoonen** [comment] 2016-05-06 12:05
Cannot reproduce in local installation. Provided link works as well, probably fixed in a previous version.

**Closed by mtoonen** 2016-05-06 12:05 UTC
Labels: bug, viewer
