### ISSUE TITLE
Filter component can't select filter operator

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#839] opened 2017-04-21 10:03 UTC
### Version
Version: 	5.0.0-beta5 (latest release: v4.8.1, dd. Thu Apr 20 2017)
Build time: 	19.04.2017 @ 13:41:33 CEST
Build by: 	Meine Toonen
Git details
Git branch: 	df7621284e320fb9f81fa83ae6350f8fd9eac60c
Git remote url 	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id: 	df76212
Git commit full id: 	df7621284e320fb9f81fa83ae6350f8fd9eac60c
Git commit time: 	19.04.2017 @ 13:38:04 CEST
Runtime information
OS info: 	Linux 3.2.0-4-amd64 amd64
Java version: 	Oracle Corporation 1.8.0_66
Servlet container info: 	Apache Tomcat/8.0.14 (Debian)
### Browser info
Firefox

### URL
http://test.flamingo4.nl/viewer/app/Test_APP
-> Layer: Wijk_2014

### Where?
Viewer

### What happened
The filter component shows a dropdown to select the attribute to filter, click it. The selected attribute is now visible.
To the right of it, there's a dropdown to select the operator to filter on, click it. The selected operator is not visible.
To the right of the operator-dropdown there is another dropdown to select the value to filter on for the selected attribute, click it. The selected value appears.

Clicking the 'apply'-button produces an error 'Error while getting SLD' (FYI, OGC SLD filtering is on)

### What did you expect?
For the selected operator to appear in the filtercomponent

### Reproduce
see above

### Server log
2017-04-21 11:54:51 ERROR nl.b3p.viewer.stripes.SldActionBean.create(SldActionBean.java:493) - Error creating sld for layer=wijk_2014, style=default, filter=null, id=null
org.geotools.filter.text.cql2.CQLException: Encountered "= null" at line 1, column 11.
Was expecting one of:
    "(" ...
    ":" ...
    <IDENTIFIER> ...
    "." ...
    "*" ...
    "/" ...
    "+" ...
    "-" ...
    ")" ...
    "not" ...
    "in" ...
    "tequals" ...
    "before" ...
    "after" ...
    "during" ...
    "like" ...
    "ilike" ...
    "exists" ...
    "does-not-exist" ...
    "is" ...
    "between" ...
    "=" "(" ...
    "=" "[" ...
    "=" <IDENTIFIER> ...
    "=" <DATE> ...
    "=" <DATE_TIME> ...
    "=" "-" ...
    "=" <INTEGER_LITERAL> ...
    "=" <FLOATING_LITERAL> ...
    "=" <STRING_LITERAL> ...
    "=" "true" ...
    "=" "false" ...
    "=" "point" ...
    "=" "linestring" ...
    "=" "polygon" ...
    "=" "multipoint" ...
    "=" "multilinestring" ...
    "=" "multipolygon" ...
    "=" "geometrycollection" ...
    "=" "envelope" ...
    ">" ...
    "<" ...
    ">=" ...
    "<=" ...
    "<>" ...
     Parsing : ("WK_CODE"=null).
	at org.geotools.filter.text.ecql.ECQLCompiler.compileFilter(ECQLCompiler.java:102)
	at org.geotools.filter.text.commons.CompilerUtil.parseFilter(CompilerUtil.java:196)
	at org.geotools.filter.text.ecql.ECQL.toFilter(ECQL.java:120)
	at org.geotools.filter.text.ecql.ECQL.toFilter(ECQL.java:99)
	at nl.b3p.viewer.stripes.SldActionBean.getSldXmlOrCreateNewSld(SldActionBean.java:285)
	at nl.b3p.viewer.stripes.SldActionBean.create(SldActionBean.java:479)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:176)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at nl.b3p.web.geotools.GeoToolsFilter.doFilter(GeoToolsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at nl.b3p.viewer.util.IPAuthenticationFilter.doFilter(IPAuthenticationFilter.java:152)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mprins** [comment] 2017-08-01 08:36
@KJLammers any chance this was using a WFS as an attribute source? it could then be a duplicate of #825

**Closed** 2017-12-13 09:19 UTC
